version: "3"

services:
  postgres:
       image: "postgres:11"
       volumes:
         - postgres:/var/lib/postgresql/data
       ports:
         - "5432:5432"
  app:
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    container_name: ecommerce-api_backend
    depends_on:
         - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/ecommerce-api
      - app-gems:/app-gems
    # env_file:
    #   - ".env"
    tmpfs:
      - "/tmp"
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgres:
  app-gems:
